"""Embed the audited fixture weights and shared HLSL; no runtime file loading."""
from pathlib import Path
import struct
import hashlib
root = Path(__file__).resolve().parents[1]
data = (root/'artifacts/relighting-world-v2/weights.bin').read_bytes()
assert len(data) == 784
values = struct.unpack('<196f', data)
shader = (root/'native/integration/GameRelightingV2.hlsl').read_text()
out = '#pragma once\n// Generated by tools/embed_game_relighting.py\n'
out += '// weights.bin SHA256: '+hashlib.sha256(data).hexdigest()+'\n'
out += 'namespace tsr::integration {\ninline constexpr float GameLightWeights[196]={\n'
out += ',\n'.join(','.join(f'{x:.9e}f' for x in values[i:i+4]) for i in range(0,196,4))
out += '\n};\ninline constexpr char GameLightShader[]=R"TSRHLSL(\n'+shader+'\n)TSRHLSL";\n}\n'
(root/'native/integration/game_relighting_embedded.h').write_text(out)
